/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const avatarGroupInjectionKey: typeof import('@nuxt/ui/runtime/composables/useAvatarGroup.js')['avatarGroupInjectionKey'];
  const buttonGroupInjectionKey: typeof import('@nuxt/ui/runtime/composables/useButtonGroup.js')['buttonGroupInjectionKey'];
  const defineLocale: typeof import('@nuxt/ui/runtime/composables/defineLocale.js')['defineLocale'];
  const defineShortcuts: typeof import('@nuxt/ui/runtime/composables/defineShortcuts.js')['defineShortcuts'];
  const extractShortcuts: typeof import('@nuxt/ui/runtime/composables/defineShortcuts.js')['extractShortcuts'];
  const formBusInjectionKey: typeof import('@nuxt/ui/runtime/composables/useFormField.js')['formBusInjectionKey'];
  const formFieldInjectionKey: typeof import('@nuxt/ui/runtime/composables/useFormField.js')['formFieldInjectionKey'];
  const formInputsInjectionKey: typeof import('@nuxt/ui/runtime/composables/useFormField.js')['formInputsInjectionKey'];
  const formLoadingInjectionKey: typeof import('@nuxt/ui/runtime/composables/useFormField.js')['formLoadingInjectionKey'];
  const formOptionsInjectionKey: typeof import('@nuxt/ui/runtime/composables/useFormField.js')['formOptionsInjectionKey'];
  const inputIdInjectionKey: typeof import('@nuxt/ui/runtime/composables/useFormField.js')['inputIdInjectionKey'];
  const kbdKeysMap: typeof import('@nuxt/ui/runtime/composables/useKbd.js')['kbdKeysMap'];
  const localeContextInjectionKey: typeof import('@nuxt/ui/runtime/composables/useLocale.js')['localeContextInjectionKey'];
  const useAppConfig: typeof import('@nuxt/ui/runtime/vue/composables/useAppConfig.js')['useAppConfig'];
  const useAvatarGroup: typeof import('@nuxt/ui/runtime/composables/useAvatarGroup.js')['useAvatarGroup'];
  const useButtonGroup: typeof import('@nuxt/ui/runtime/composables/useButtonGroup.js')['useButtonGroup'];
  const useComponentIcons: typeof import('@nuxt/ui/runtime/composables/useComponentIcons.js')['useComponentIcons'];
  const useFormField: typeof import('@nuxt/ui/runtime/composables/useFormField.js')['useFormField'];
  const useKbd: typeof import('@nuxt/ui/runtime/composables/useKbd.js')['useKbd'];
  const useLocale: typeof import('@nuxt/ui/runtime/composables/useLocale.js')['useLocale'];
  const useOverlay: typeof import('@nuxt/ui/runtime/composables/useOverlay.js')['useOverlay'];
  const useToast: typeof import('@nuxt/ui/runtime/composables/useToast.js')['useToast'];
}
// for type re-export
declare global {
  // @ts-ignore
  export type {
    ShortcutConfig,
    ShortcutsConfig,
    ShortcutsOptions,
  } from '../node_modules/@nuxt/ui/dist/runtime/composables/defineShortcuts.d';
  import('@nuxt/ui/runtime/composables/defineShortcuts.js');
  // @ts-ignore
  export type { UseComponentIconsProps } from '../node_modules/@nuxt/ui/dist/runtime/composables/useComponentIcons.d';
  import('@nuxt/ui/runtime/composables/useComponentIcons.js');
  // @ts-ignore
  export type {
    KbdKey,
    KbdKeySpecific,
  } from '../node_modules/@nuxt/ui/dist/runtime/composables/useKbd.d';
  import('@nuxt/ui/runtime/composables/useKbd.js');
  // @ts-ignore
  export type {
    OverlayOptions,
    Overlay,
  } from '../node_modules/@nuxt/ui/dist/runtime/composables/useOverlay.d';
  import('@nuxt/ui/runtime/composables/useOverlay.js');
  // @ts-ignore
  export type { Toast } from '../node_modules/@nuxt/ui/dist/runtime/composables/useToast.d';
  import('@nuxt/ui/runtime/composables/useToast.js');
}
