/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UApp: typeof import('@nuxt/ui/runtime/components/App.vue.js')['default']
    UButton: typeof import('@nuxt/ui/runtime/components/Button.vue.js')['default']
    UIcon: typeof import('@nuxt/ui/runtime/vue/components/Icon.vue.js')['default']
    ULinkBase: typeof import('@nuxt/ui/runtime/components/LinkBase.vue.js')['default']
  }
}
